services:
  web:
    build: .
    container_name: bonus_system_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_data:/app/staticfiles
    environment:
      DJANGO_SETTINGS_MODULE: bonus_system.settings
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  static_data:
